# Generated by Django 2.2.2 on 2019-09-22 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliant',
            name='pol_officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='public.Police'),
        ),
    ]
