# Generated by Django 2.2.2 on 2019-09-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20190922_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliant',
            name='complainee_addr',
            field=models.CharField(default='no-name', max_length=250),
        ),
        migrations.AlterField(
            model_name='compliant',
            name='complainee_name',
            field=models.CharField(default='no-name', max_length=30),
        ),
    ]
