# Generated by Django 2.2.2 on 2019-09-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20190922_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliant',
            name='complainee_addr',
            field=models.CharField(default='No name', max_length=250),
        ),
        migrations.AlterField(
            model_name='compliant',
            name='complainee_name',
            field=models.CharField(default='No name', max_length=30),
        ),
    ]
