# Generated by Django 2.2.2 on 2019-09-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_auto_20190923_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=70)),
                ('last_seen', models.DateField()),
                ('id_mark', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='unidentifiedbodies',
            name='date_of_death',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
