# Generated by Django 2.2.2 on 2019-10-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_auto_20190923_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='img',
            field=models.ImageField(default=None, upload_to='criminal_imgs'),
            preserve_default=False,
        ),
    ]
