# Generated by Django 2.2.2 on 2019-10-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_criminal_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminal',
            name='img',
            field=models.ImageField(blank=True, upload_to='criminal_imgs/'),
        ),
    ]
