# Generated by Django 2.2.2 on 2019-10-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_auto_20191005_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='last_seen',
            field=models.DateField(null=True),
        ),
    ]
